### ISSUE TITLE
node_modules and git ignore

### ISSUE THREAD

**Issue by aisflat439** [kevindeal/Fish-market-react-app#2]
Hey Kev!
Take a min to google `.gitignore` and understand what they are. They're pretty straightforward to understand but let me know if you have any questions.

Here's some basic content for one. The key line is the `/node_modules` one which you're currently commiting and should not. Those files are meant to be local on your machine, not in the repo.

```
# See https://help.github.com/articles/ignoring-files/ for more about ignoring files.

# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# production
/build

# misc
.DS_Store
.env.local
.env.development.local
.env.test.local
.env.production.local

npm-debug.log*
yarn-debug.log*
yarn-error.log*

```

**Comment by kevindeal** [comment]
@aisflat439 that looks like I took care of it. I should have created a new branch for that.
